export const DEFS : Record<string, string> = {
	"abbba": "Abbott's Babbler",
	"ahgpi": "Ashy-headed Green Pigeon",
	"alete": "Aleutian Tern",
	"ampfl": "Amur Paradise Flycatcher",
	"amufa": "Amur Falcon",
	"amust": "Amur Stonechat",
	"arcwa": "Arctic Warbler",
	"arebu": "Asian Red-eyed Bulbul",
	"asbfl": "Asian Brown Flycatcher",
	"asecu": "Asian Emerald Cuckoo",
	"asfbl": "Asian Fairy-bluebird",
	"asgst": "Asian Glossy Starling",
	"ashdr": "Ashy Drongo",
	"ashma": "Asian House Martin",
	"ashmi": "Ashy Minivet",
	"ashta": "Ashy Tailorbird",
	"asido": "Asian Dowitcher",
	"asiko": "Asian Koel",
	"asiop": "Asian Openbill",
	"aspsw": "Asian Palm Swift",
	"babcr": "Band-bellied Crake",
	"babcu": "Banded Bay Cuckoo",
	"baeow": "Barred Eagle-Owl",
	"baicr": "Baillon's Crake",
	"banwo": "Banded Woodpecker",
	"barbr": "Black-and-red Broadbill",
	"barbu": "Barred Buttonquail",
	"barsw": "Barn Swallow",
	"batgo": "Bar-tailed Godwit",
	"batha": "Bat Hawk",
	"bawbu": "Black-and-white Bulbul",
	"bawfl": "Blue-and-white Flycatcher",
	"baywe": "Baya Weaver",
	"bbrwa": "Black-browed Reed Warbler",
	"bchpa": "Blue-crowned Hanging Parrot",
	"bcjfl": "Brown-chested Jungle Flycatcher",
	"bcnhe": "Black-crowned Night Heron",
	"bescu": "Beach Stone-curlew",
	"besra": "Besra",
	"blaba": "Black Baza",
	"blabi": "Black Bittern",
	"bladr": "Black Drongo",
	"blaho": "Black Hornbill",
	"blaki": "Black Kite",
	"blare": "Black Redstart",
	"blcbu": "Black-crested Bulbul",
	"blcki": "Black-capped Kingfisher",
	"bleki": "Blue-eared Kingfisher",
	"bhbul": "Black-headed Bulbul",
	"bhbun": "Black-headed Bunting",
	"blhgu": "Black-headed Gull",
	"blnmo": "Black-naped Monarch",
	"blnor": "Black-naped Oriole",
	"blnsw": "Black-nest Swiftlet",
	"blnte": "Black-naped Tern",
	"blpfl": "Blyth's Paradise Flycatcher",
	"blrpa": "Blue-rumped Parrot",
	"blrth": "Blue Rock Thrush",
	"bltfa": "Black-thighed Falconet",
	"bltgo": "Black-tailed Godwit",
	"blwki": "Black-winged Kite",
	"blwle": "Blue-winged Leafbird",
	"blwpi": "Blue-winged Pitta",
	"blwst": "Black-winged Stilt",
	"booea": "Booted Eagle",
	"boowa": "Booted Warbler",
	"braki": "Brahminy Kite",
	"brast": "Brahminy Starling",
	"brbne": "Brown-backed Needletail",
	"brbsa": "Broad-billed Sandpiper",
	"brhgu": "Brown-headed Gull",
	"brhow": "Brown Hawk-Owl",
	"brite": "Bridled Tern",
	"brobo": "Brown Booby",
	"brosh": "Brown Shrike",
	"brsfl": "Brown-streaked Flycatcher",
	"brtsu": "Brown-throated Sunbird",
	"brwow": "Brown Wood Owl",
	"btabe": "Blue-tailed Bee-eater",
	"bthbe": "Blue-throated Bee-eater",
	"bufow": "Buffy Fish Owl",
	"bulpe": "Bulwer's Petrel",
	"burwo": "Buff-rumped Woodpecker",
	"buvbu": "Buff-vented Bulbul",
	"bwfsh": "Black-winged Flycatcher-shrike",
	"caste": "Caspian Tern",
	"chbfl": "Chinese Blue Flycatcher",
	"chbma": "Chestnut-bellied Malkoha",
	"chcst": "Chestnut-cheeked Starling",
	"chemu": "Chestnut Munia",
	"chgpi": "Cinnamon-headed Green Pigeon",
	"chhea": "Changeable Hawk-Eagle",
	"chibl": "Chinese Blackbird",
	"chieg": "Chinese Egret",
	"chihw": "Chinese Hwamei",
	"chisp": "Chinese Sparrowhawk",
	"chphe": "Chinese Pond Heron",
	"chwba": "Chestnut-winged Babbler",
	"chwcu": "Chestnut-winged Cuckoo",
	"cinbi": "Cinnamon Bittern",
	"cinbu": "Cinereous Bulbul",
	"cinvu": "Cinereous Vulture",
	"citwa": "Citrine Wagtail",
	"coclo": "Coconut Lorikeet",
	"coedo": "Common Emerald Dove",
	"cohmy": "Common Hill Myna",
	"colki": "Collared Kingfisher",
	"combu": "Common Buzzard",
	"comfl": "Common Flameback",
	"comgr": "Common Greenshank",
	"comio": "Common Iora",
	"comke": "Common Kestrel",
	"comki": "Common Kingfisher",
	"commo": "Common Moorhen",
	"commy": "Common Myna",
	"comre": "Common Redshank",
	"comsa": "Common Sandpiper",
	"comsn": "Common Snipe",
	"comst": "Common Starling",
	"comsw": "Common Swift",
	"comta": "Common Tailorbird",
	"comte": "Common Tern",
	"copba": "Coppersmith Barbet",
	"copgo": "Cotton Pygmy Goose",
	"corpl": "Common Ringed Plover",
	"cotsu": "Copper-throated Sunbird",
	"crbdr": "Crow-billed Drongo",
	"crego": "Crested Goshawk",
	"crhbu": "Crested Honey Buzzard",
	"crisu": "Crimson Sunbird",
	"crsea": "Crested Serpent Eagle",
	"crvbu": "Cream-vented Bulbul",
	"crwwo": "Crimson-winged Woodpecker",
	"cursa": "Curlew Sandpiper",
	"danta": "Dark-necked Tailorbird",
	"dasfl": "Dark-sided Flycatcher",
	"daure": "Daurian Redstart",
	"daust": "Daurian Starling",
	"duswa": "Dusky Warbler",
	"eabow": "Eastern Barn Owl",
	"eaceg": "Eastern Cattle Egret",
	"eacwa": "Eastern Crowned Warbler",
	"eaiea": "Eastern Imperial Eagle",
	"eamha": "Eastern Marsh Harrier",
	"easbu": "Eastern Buzzard",
	"eaywa": "Eastern Yellow Wagtail",
	"ednsw": "Edible-nest Swiftlet",
	"eurco": "Eurasian Coot",
	"eurcu": "Eurasian Curlew",
	"eurho": "Eurasian Hobby",
	"eursk": "Eurasian Skylark",
	"eursp": "Eurasian Sparrowhawk",
	"eurwh": "Eurasian Whimbrel",
	"eurwi": "Eurasian Wigeon",
	"eutsp": "Eurasian Tree Sparrow",
	"eyeth": "Eyebrowed Thrush",
	"faecu": "Far Eastern Curlew",
	"faipi": "Fairy Pitta",
	"ferfl": "Ferruginous Flycatcher",
	"forwa": "Forest Wagtail",
	"gadwa": "Gadwall",
	"garga": "Garganey",
	"ghfea": "Grey-headed Fish Eagle",
	"gloib": "Glossy Ibis",
	"gobge": "Golden-bellied Gerygone",
	"gobwe": "Golden-backed Weaver",
	"grbfl": "Green-backed Flycatcher",
	"grbhe": "Great-billed Heron",
	"grcte": "Greater Crested Tern",
	"grebr": "Green Broadbill",
	"greco": "Greater Coucal",
	"greeg": "Great Egret",
	"grehe": "Grey Heron",
	"greho": "Great Hornbill",
	"grekn": "Great Knot",
	"greni": "Grey Nightjar",
	"grepl": "Grey Plover",
	"gresa": "Green Sandpiper",
	"grewa": "Grey Wagtail",
	"grfbu": "Grey-faced Buzzard",
	"grgle": "Greater Green Leafbird",
	"grhla": "Grey-headed Lapwing",
	"grhsw": "Grey-headed Swamphen",
	"gripi": "Green Imperial Pigeon",
	"grpsn": "Greater Painted-snipe",
	"grrtr": "Grey-rumped Treeswift",
	"grsea": "Greater Spotted Eagle",
	"grsfl": "Grey-streaked Flycatcher",
	"grspl": "Greater Sand Plover",
	"grswo": "Great Slaty Woodpecker",
	"grtdr": "Greater Racket-tailed Drongo",
	"grtta": "Grey-tailed Tattler",
	"gubte": "Gull-billed Tern",
	"hacdr": "Hair-crested Drongo",
	"himcu": "Himalayan Cuckoo",
	"himvu": "Himalayan Vulture",
	"hobcu": "Horsfield's Bronze Cuckoo",
	"hohcu": "Hodgson's Hawk-Cuckoo",
	"hoopi": "Hooded Pitta",
	"houcr": "House Crow",
	"housp": "House Sparrow",
	"housw": "House Swift",
	"indcu": "Indian Cuckoo",
	"inpfl": "Indian Paradise Flycatcher",
	"inphe": "Indian Pond Heron",
	"integ": "Intermediate Egret",
	"jaccu": "Jacobin Cuckoo",
	"jafdo": "Jambu Fruit Dove",
	"japfl": "Japanese Paradise Flycatcher",
	"japhe": "Javan Pond Heron",
	"japsp": "Japanese Sparrowhawk",
	"japti": "Japanese Tit",
	"javmu": "Javan Munia",
	"javmy": "Javan Myna",
	"javpl": "Javan Plover",
	"jerba": "Jerdon's Baza",
	"kenpl": "Kentish Plover",
	"kinqu": "King Quail",
	"labcr": "Large-billed Crow",
	"lacwo": "Laced Woodpecker",
	"lahcu": "Large Hawk-Cuckoo",
	"lanwa": "Lanceolated Warbler",
	"larwo": "Large Woodshrike",
	"latni": "Large-tailed Nightjar",
	"lecte": "Lesser Crested Tern",
	"legle": "Lesser Green Leafbird",
	"lesad": "Lesser Adjutant",
	"lesco": "Lesser Coucal",
	"lescu": "Lesser Cuckooshrike",
	"lesfr": "Lesser Frigatebird",
	"leske": "Lesser Kestrel",
	"lespl": "Lesser Sand Plover",
	"lewdu": "Lesser Whistling Duck",
	"libcu": "Little Bronze Cuckoo",
	"ligpi": "Little Green Pigeon",
	"linba": "Lineated Barbet",
	"lirpl": "Little Ringed Plover",
	"litcu": "Little Curlew",
	"liteg": "Little Egret",
	"litgr": "Little Grebe",
	"litsp": "Little Spiderhunter",
	"litst": "Little Stint",
	"litte": "Little Tern",
	"loeow": "Long-eared Owl",
	"lotja": "Long-tailed Jaeger",
	"lotpa": "Long-tailed Parakeet",
	"lotsh": "Long-tailed Shrike",
	"lotst": "Long-toed Stint",
	"mabfl": "Mangrove Blue Flycatcher",
	"mabma": "Malayan Black Magpie",
	"maeni": "Malaysian Eared Nightjar",
	"mahcu": "Malaysian Hawk-Cuckoo",
	"malpl": "Malaysian Plover",
	"manhe": "Malayan Night Heron",
	"manpi": "Mangrove Pitta",
	"manwh": "Mangrove Whistler",
	"mapfa": "Malaysian Pied Fantail",
	"marsa": "Marsh Sandpiper",
	"masfi": "Masked Finfoot",
	"masla": "Masked Lapwing",
	"milst": "Milky Stork",
	"moipi": "Mountain Imperial Pigeon",
	"monpa": "Monk Parakeet",
	"mouba": "Moustached Babbler",
	"mugfl": "Mugimaki Flycatcher",
	"narfl": "Narcissus Flycatcher",
	"norbo": "Northern Boobook",
	"norgr": "Nordmann's Greenshank",
	"norpi": "Northern Pintail",
	"norsh": "Northern Shoveler",
	"obgpi": "Orange-breasted Green Pigeon",
	"olbpi": "Olive-backed Pipit",
	"olbsu": "Olive-backed Sunbird",
	"olwbu": "Olive-winged Bulbul",
	"orbfl": "Orange-bellied Flowerpecker",
	"ordki": "Oriental Dwarf Kingfisher",
	"orhth": "Orange-headed Thrush",
	"orida": "Oriental Darter",
	"orido": "Oriental Dollarbird",
	"oripl": "Oriental Plover",
	"oripr": "Oriental Pratincole",
	"ormro": "Oriental Magpie-Robin",
	"orpho": "Oriental Pied Hornbill",
	"orrwa": "Oriental Reed Warbler",
	"orsow": "Oriental Scops Owl",
	"ortdo": "Oriental Turtle Dove",
	"paswi": "Pacific Swift",
	"paswa": "Pacific Swallow",
	"padpi": "Paddyfield Pipit",
	"pagpl": "Pacific Golden Plover",
	"pagwa": "Pallas's Grasshopper Warbler",
	"paist": "Painted Stork",
	"parhe": "Pacific Reef Heron",
	"parja": "Parasitic Jaeger",
	"pecsa": "Pectoral Sandpiper",
	"perfa": "Peregrine Falcon",
	"phtja": "Pheasant-tailed Jacana",
	"pieha": "Pied Harrier",
	"pieki": "Pied Kingfisher",
	"piest": "Pied Stilt",
	"pietr": "Pied Triller",
	"piipi": "Pied Imperial Pigeon",
	"pitsn": "Pin-tailed Snipe",
	"placu": "Plaintive Cuckoo",
	"pllwa": "Pale-legged Leaf Warbler",
	"pltsw": "Plume-toed Swiftlet",
	"pngpi": "Pink-necked Green Pigeon",
	"pomja": "Pomarine Jaeger",
	"pstba": "Pin-striped Tit-Babbler",
	"purhe": "Purple Heron",
	"rebpa": "Red-breasted Parakeet",
	"rebst": "Red-billed Starling",
	"recba": "Red-crowned Barbet",
	"recdo": "Red Collared Dove",
	"redav": "Red Avadavat",
	"redju": "Red Junglefowl",
	"redkn": "Red Knot",
	"refbo": "Red-footed Booby",
	"relcr": "Red-legged Crake",
	"renph": "Red-necked Phalarope",
	"renst": "Red-necked Stint",
	"rersw": "Red-rumped Swallow",
	"retpi": "Red-throated Pipit",
	"rewbu": "Red-whiskered Bulbul",
	"rewla": "Red-wattled Lapwing",
	"rocdo": "Rock Dove",
	"rorpa": "Rose-ringed Parakeet",
	"rosst": "Rosy Starling",
	"rubcr": "Ruddy-breasted Crake",
	"rubcu": "Rusty-breasted Cuckoo",
	"rubea": "Rufous-bellied Eagle",
	"rucsu": "Ruby-cheeked Sunbird",
	"rudki": "Ruddy Kingfisher",
	"rudtu": "Ruddy Turnstone",
	"ruff	": "uff",
	"rufwo": "Rufous Woodpecker",
	"rutta": "Rufous-tailed Tailorbird",
	"salwa": "Sakhalin Leaf Warbler",
	"sande": "Sanderling",
	"sanma": "Sand Martin",
	"savni": "Savanna Nightjar",
	"scami": "Scarlet Minivet",
	"sbrfl": "Scarlet-breasted Flowerpecker",
	"sbafl": "Scarlet-backed Flowerpecker",
	"scbmu": "Scaly-breasted Munia",
	"sheow": "Short-eared Owl",
	"shikr": "Shikra",
	"shtba": "Short-tailed Babbler",
	"shtsa": "Sharp-tailed Sandpiper",
	"shtsh": "Short-tailed Shearwater",
	"sibne": "Silver-backed Needletail",
	"sibro": "Siberian Blue Robin",
	"sibth": "Siberian Thrush",
	"sihma": "Siberian House Martin",
	"sirsp": "Silver-rumped Spinetail",
	"slbra": "Slaty-breasted Rail",
	"sllcr": "Slaty-legged Crake",
	"smapr": "Small Pratincole",
	"sohbu": "Sooty-headed Bulbul",
	"spbsa": "Spoon-billed Sandpiper",
	"spodo": "Spotted Dove",
	"spofl": "Spotted Flycatcher",
	"spore": "Spotted Redshank",
	"spwow": "Spotted Wood Owl",
	"stbki": "Stork-billed Kingfisher",
	"stdcu": "Square-tailed Drongo-Cuckoo",
	"steea": "Steppe Eagle",
	"stest": "Stejneger's Stonechat",
	"sthbu": "Straw-headed Bulbul",
	"strbu": "Streaked Bulbul",
	"strhe": "Striated Heron",
	"strwe": "Streaked Weaver",
	"stsea": "Short-toed Snake Eagle",
	"supwo": "Sunda Pygmy Woodpecker",
	"susow": "Sunda Scops Owl",
	"swisn": "Swinhoe's Snipe",
	"swspe": "Swinhoe's Storm Petrel",
	"swwey": "Swinhoe's White-eye",
	"taifl": "Taiga Flycatcher",
	"tanco": "Tanimbar Corella",
	"tbgpi": "Thick-billed Green Pigeon",
	"temst": "Temminck's Stint",
	"tersa": "Terek Sandpiper",
	"thbfl": "Thick-billed Flowerpecker",
	"thbsp": "Thick-billed Spiderhunter",
	"tigsh": "Tiger Shrike",
	"trepi": "Tree Pipit",
	"tufdu": "Tufted Duck",
	"vahsu": "Van Hasselt's Sunbird",
	"vefnu": "Velvet-fronted Nuthatch",
	"verfl": "Verditer Flycatcher",
	"viocu": "Violet Cuckoo",
	"vosbi": "Von Schrenck's Bittern",
	"water": "Watercock",
	"wawdu": "Wandering Whistling Duck",
	"wbsea": "White-bellied Sea Eagle",
	"wesos": "Western Osprey",
	"wetsh": "Wedge-tailed Shearwater",
	"whbcr": "White-browed Crake",
	"whber": "White-bellied Erpornis",
	"whbwa": "White-breasted Waterhen",
	"whbwo": "White-bellied Woodpecker",
	"whcba": "White-chested Babbler",
	"whcla": "White-crested Laughingthrush",
	"whcst": "White-cheeked Starling",
	"whfpl": "White-faced Plover",
	"whhmu": "White-headed Munia",
	"white": "Whiskered Tern",
	"whitr": "Whiskered Treeswift",
	"whiwa": "White Wagtail",
	"whrmu": "White-rumped Munia",
	"whrsh": "White-rumped Shama",
	"whsst": "White-shouldered Starling",
	"whtki": "White-throated Kingfisher",
	"whtne": "White-throated Needletail",
	"whttr": "White-tailed Tropicbird",
	"whwte": "White-winged Tern",
	"woosa": "Wood Sandpiper",
	"wtrth": "White-throated Rock Thrush",
	"yebpr": "Yellow-bellied Prinia",
	"yebwa": "Yellow-browed Warbler",
	"yeesp": "Yellow-eared Spiderhunter",
	"yelbi": "Yellow Bittern",
	"yerfl": "Yellow-rumped Flycatcher",
	"yevbu": "Yellow-vented Bulbul",
	"yevfl": "Yellow-vented Flowerpecker",
	"zapfl": "Zappey's Flycatcher",
	"zebdo": "Zebra Dove",
	"zitci": "Zitting Cisticola",	
}

